import Head from "next/head";
import Image from "next/image";
import me from "../public/mountains.jpg";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>My Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div style={{ marginBottom: 50 }}>
          <Image
            alt="Mountains"
            src={me}
            layout="fixed"
            width={1000}
            height={407}
          />
        </div>

        <h1 className={styles.title}>Сайн байна уу? Норовсүрэн байна.</h1>

        <p className={styles.description}>
          National University of Mongolia - Software Engineering (2017-2021){" "}
        </p>

        <div className={styles.grid}>
          <a href="https://github.com/nogy88" className={styles.card}>
            <h2>Github profile &rarr;</h2>
            <p>Github дээр хийсэн прожектуудыг харах</p>
          </a>

          <a href="https://www.m.me/finnesaias/" className={styles.card}>
            <h2>Messenger &rarr;</h2>
            <p>Facebook Messenger-ээр холбогдох</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
